# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tvec_hat_from_tvec <- function(theta, tvec, observations, K1_fn, K2_solve_fn) {
    .Call(`_saddlepoint_tvec_hat_from_tvec`, theta, tvec, observations, K1_fn, K2_solve_fn)
}

tapedSaddlepointSolve <- function(theta, observations, K2_solve_fn, saddlepoint_solve_fn, cgf_obj) {
    .Call(`_saddlepoint_tapedSaddlepointSolve`, theta, observations, K2_solve_fn, saddlepoint_solve_fn, cgf_obj)
}

matinv_TMBad <- function(x) {
    .Call(`_saddlepoint_matinv_TMBad`, x)
}

matinv_double <- function(x) {
    .Call(`_saddlepoint_matinv_double`, x)
}

