# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

makeAdaptorUsingRfunctions <- function(fn, grad_fn) {
    .Call(`_saddlepoint_makeAdaptorUsingRfunctions`, fn, grad_fn)
}

makeSubvectorAdaptor <- function(pos, len) {
    .Call(`_saddlepoint_makeSubvectorAdaptor`, pos, len)
}

makeVectorSubsetByIndicesAdaptor <- function(indices) {
    .Call(`_saddlepoint_makeVectorSubsetByIndicesAdaptor`, indices)
}

makeSavedVectorAdaptor <- function(fixed_parameter_values) {
    .Call(`_saddlepoint_makeSavedVectorAdaptor`, fixed_parameter_values)
}

adapt_CGF <- function(base_cgf, adaptor) {
    .Call(`_saddlepoint_adapt_CGF`, base_cgf, adaptor)
}

makeADFunK1 <- function(tvec, theta, modelCGF) {
    .Call(`_saddlepoint_makeADFunK1`, tvec, theta, modelCGF)
}

#' Compute K1 and its gradient
#'
#' This function computes the K1 function and its gradient for a given combined vector of `tvec` and `theta`.
#' The K1 function is computed using a `CppAD::ADFun<double>` object created by the `make.ADFunK1()`-R function.
#'
#' This function is primarily intended for internal use.
#'
#' @param combined_vector A numeric vector of `tvec` and `theta` in that order.
#' @param ADfunK1 An `XPtr` to a `CppAD::ADFun<double>` object, typically the result of the `makeADFunK1()` function.
#'
#' @return A list with two elements: `fn`, the value of the K1 function, and `gr`, the gradient of the K1 function.
#' @keywords internal
K1_with_gradient <- function(combined_vector, ADfunK1) {
    .Call(`_saddlepoint_K1_with_gradient`, combined_vector, ADfunK1)
}

makeADFunNegll <- function(tvec, theta, modelCGF) {
    .Call(`_saddlepoint_makeADFunNegll`, tvec, theta, modelCGF)
}

#' Compute negative log-likelihood and its gradient
#'
#' This function computes the negative log-likelihood function and its gradient for a given combined vector of `tvec` and `theta`.
#'
#' This function is primarily intended for internal use.
#'
#' @param combined_vector A numeric vector of `tvec` and `theta` in that order.
#' @param ADfun_negll An `XPtr` to a `CppAD::ADFun<double>` object, typically the result of the `make.ADFunNegll()`-R function.
#'
#' @return A list with two elements: `objective`, the value of the negative log-likelihood function, and `gradient`, the gradient of the function.
#' @keywords internal
negll_with_gradient <- function(combined_vector, ADfun_negll) {
    .Call(`_saddlepoint_negll_with_gradient`, combined_vector, ADfun_negll)
}

makeADFunIneqConstraint <- function(tvec, theta, modelCGF) {
    .Call(`_saddlepoint_makeADFunIneqConstraint`, tvec, theta, modelCGF)
}

#' Compute inequality constraint and its gradient
#'
#' This function computes the inequality constraint function and its gradient for a given combined vector of `tvec` and `theta`.
#'
#' This function is primarily intended for internal use.
#'
#' @param combined_vector A numeric vector of `tvec` and `theta` in that order.
#' @param ADfun_ineqConstraint An `XPtr` to a `CppAD::ADFun<double>` object, typically the result of the `make.ADFunIneqConstraint()`-R function.
#'
#' @return A list with two elements: `fn`, the value of the inequality constraint function, and `gr`, the gradient of the function.
#' @keywords internal
ineqConstraint_with_gradient <- function(combined_vector, ADfun_ineqConstraint) {
    .Call(`_saddlepoint_ineqConstraint_with_gradient`, combined_vector, ADfun_ineqConstraint)
}

make_BinomialCGF <- function() {
    .Call(`_saddlepoint_make_BinomialCGF`)
}

make_BinomialNonIdenticalCGF <- function() {
    .Call(`_saddlepoint_make_BinomialNonIdenticalCGF`)
}

make_BinomialModelCGF <- function(n_adaptor, prob_adaptor) {
    .Call(`_saddlepoint_make_BinomialModelCGF`, n_adaptor, prob_adaptor)
}

make_PoissonCGF <- function() {
    .Call(`_saddlepoint_make_PoissonCGF`)
}

make_PoissonNonIdenticalCGF <- function() {
    .Call(`_saddlepoint_make_PoissonNonIdenticalCGF`)
}

make_PoissonModelCGF <- function(lambda_adaptor) {
    .Call(`_saddlepoint_make_PoissonModelCGF`, lambda_adaptor)
}

make_ExponentialCGF <- function() {
    .Call(`_saddlepoint_make_ExponentialCGF`)
}

make_ExponentialNonIdenticalCGF <- function() {
    .Call(`_saddlepoint_make_ExponentialNonIdenticalCGF`)
}

make_ExponentialModelCGF <- function(lambda_adaptor) {
    .Call(`_saddlepoint_make_ExponentialModelCGF`, lambda_adaptor)
}

make_GeometricCGF <- function() {
    .Call(`_saddlepoint_make_GeometricCGF`)
}

make_GeometricNonIdenticalCGF <- function() {
    .Call(`_saddlepoint_make_GeometricNonIdenticalCGF`)
}

make_GeometricModelCGF <- function(p_adaptor) {
    .Call(`_saddlepoint_make_GeometricModelCGF`, p_adaptor)
}

make_GeometricNonIdenticalModelCGF <- function(p_adaptor) {
    .Call(`_saddlepoint_make_GeometricNonIdenticalModelCGF`, p_adaptor)
}

make_GammaCGF <- function() {
    .Call(`_saddlepoint_make_GammaCGF`)
}

make_GammaModelCGF <- function(shape_adaptor, rate_adaptor) {
    .Call(`_saddlepoint_make_GammaModelCGF`, shape_adaptor, rate_adaptor)
}

make_MultinomialCGF <- function() {
    .Call(`_saddlepoint_make_MultinomialCGF`)
}

make_MultinomialModelCGF <- function(n_adaptor, probVector_adaptor) {
    .Call(`_saddlepoint_make_MultinomialModelCGF`, n_adaptor, probVector_adaptor)
}

make_SubunitaryMultinomialModelCGF <- function(n_adaptor, probVector_adaptor) {
    .Call(`_saddlepoint_make_SubunitaryMultinomialModelCGF`, n_adaptor, probVector_adaptor)
}

K <- function(tvec, parameter_vector, base_cgf) {
    .Call(`_saddlepoint_K`, tvec, parameter_vector, base_cgf)
}

K1 <- function(tvec, parameter_vector, base_cgf) {
    .Call(`_saddlepoint_K1`, tvec, parameter_vector, base_cgf)
}

K2 <- function(tvec, parameter_vector, base_cgf) {
    .Call(`_saddlepoint_K2`, tvec, parameter_vector, base_cgf)
}

ineq_constraint <- function(tvec, parameter_vector, base_cgf) {
    .Call(`_saddlepoint_ineq_constraint`, tvec, parameter_vector, base_cgf)
}

neg_ll <- function(tvec, parameter_vector, base_cgf) {
    .Call(`_saddlepoint_neg_ll`, tvec, parameter_vector, base_cgf)
}

func_T <- function(tvec, parameter_vector, base_cgf) {
    .Call(`_saddlepoint_func_T`, tvec, parameter_vector, base_cgf)
}

K4operatorAABB <- function(tvec, a1, a2, parameter_vector, base_cgf) {
    .Call(`_saddlepoint_K4operatorAABB`, tvec, a1, a2, parameter_vector, base_cgf)
}

K3K3operatorAABBCC <- function(tvec, a1, a2, a3, parameter_vector, base_cgf) {
    .Call(`_saddlepoint_K3K3operatorAABBCC`, tvec, a1, a2, a3, parameter_vector, base_cgf)
}

make_sum_of_iidCGF <- function(base_cgf, n) {
    .Call(`_saddlepoint_make_sum_of_iidCGF`, base_cgf, n)
}

make_sum_of_independentCGF <- function(cgf_list) {
    .Call(`_saddlepoint_make_sum_of_independentCGF`, cgf_list)
}

make_ConcatenationCGF <- function(cgf_length_list) {
    .Call(`_saddlepoint_make_ConcatenationCGF`, cgf_length_list)
}

make_linearly_mappedCGF <- function(base_cgf, Amat) {
    .Call(`_saddlepoint_make_linearly_mappedCGF`, base_cgf, Amat)
}

make_randomly_stopped_sumCGF <- function(count_base_cgf, summand_base_cgf) {
    .Call(`_saddlepoint_make_randomly_stopped_sumCGF`, count_base_cgf, summand_base_cgf)
}

make_scalar_to_iidCGF <- function(scalar_base_cgf) {
    .Call(`_saddlepoint_make_scalar_to_iidCGF`, scalar_base_cgf)
}

make_iidReplicatesCGF <- function(base_cgf, block_size) {
    .Call(`_saddlepoint_make_iidReplicatesCGF`, base_cgf, block_size)
}

computeFuncTGradient <- function(tvec, theta, observations, modelCGF) {
    .Call(`_saddlepoint_computeFuncTGradient`, tvec, theta, observations, modelCGF)
}

