# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sp_getValues <- function(x) {
    .Call(`_saddlepoint_sp_getValues`, x)
}

